# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: CDwi\blog
browsertitle: Blog | CoderDojo Wiesbaden
email: blog@coderdojo-wiesbaden.de

description:
  main: Der Blog des CoderDojos Wiesbadens.<br/>
  sub: Lies ihn.<br/>Lass dich inspirieren.<br/>Sei beeindruckt. Vielleicht.
searchdescription: >-
  Der Blog des Wiesbadener CoderDojos.
  Lerne mit anderen Jugendlichen in entspannter Atmosphäre, zu Programmieren.

baseurl: "/" # the subpath of your site, e.g. /blog
url: https://blog.cdwi.de # the base hostname & protocol for your site, e.g. http://example.com
mainurl: https://coderdojo-wiesbaden.de
shorturl: cdwi.de

github:
  org: CoderDojo-Wiesbaden

# Build settings
markdown: kramdown
paginate: 25
theme: jekyll-theme-hyde
plugins:
  - jekyll-feed
  - jekyll-paginate


tag_page_layout: tags
tag_page_dir: tag

defaults:
  - scope:
      path: "/authors"
    values:
      permalink: "/autor/:title"


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
